version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:80
    ports:
      - 80:80
    networks:
      - backend
networks:
  backend:
    driver: bridge
