# Generated by Django 4.2.1 on 2023-06-23 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_food'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ('name',), 'verbose_name': 'Food', 'verbose_name_plural': 'Food'},
        ),
    ]
