# Generated by Django 4.2.1 on 2023-06-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_food_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
    ]
