# Generated by Django 4.2.1 on 2023-06-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_food_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('name', models.CharField(blank=True, default='', max_length=254, verbose_name='name')),
                ('price', models.IntegerField(blank=True, default=0, verbose_name='price')),
                ('file', models.ImageField(blank=True, default='', upload_to='images/dessert', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Dessert',
                'verbose_name_plural': 'Dessert',
                'ordering': ('name',),
            },
        ),
    ]
