# Generated by Django 4.2.1 on 2023-06-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_textgoal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textgoal',
            name='description',
            field=models.CharField(blank=True, default='', max_length=600, verbose_name='description'),
        ),
    ]
